server:
  port: 8082

spring:
  application:
    name: product-app
  cloud:
    uri: http://localhost:8888
    openfeign:
      client:
        config:
          default:
            connectTimeout: 60000
            readTimeout: 5000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      shared:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        recordExceptions:
          - java.net.ConnectException
  retry:
    configs:
      shared:
        maxAttempts: 3
        waitDuration: 3s
        recordExceptions:
          - java.net.SocketTimeoutException

  management:
  endpoints:
    web:
      exposure:
        include: '*'
          
